[package]
name = "hooky"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.94"
utils = { path= "../utils" }
walkdir = "2.3.2"
log = "0.4.17"
ctrlc = "3.2.5"

